server:
  port: 9000
spring:
  application:
    name: api-manager-auth
  datasource:
    url: jdbc:mysql://minnan.site:3306/api_manager?serverTimezone=Asia/Shanghai
    username: Minnan
    password: minnan
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 600000
  redis:
    host: minnan.site
    port: 6379
    database: 6
    password: minnan
  cache:
    type: redis
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9030/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
feign:
  hystrix:
    enabled: true

swagger:
  base-package: site.minnan.apimanager.userinterface.fascade

jwt:
  header: Authorization
  expiration: 604800
  secret: min107
  authorized: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true