POST {{authUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "min",
  "password": "c663b11dff4be0badcf652212a2c1102"
}

> {% client.global.set("token", response.body.data.token) %}

###
POST {{projectUrl}}/project/addProject
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "projectName": "1004测试项目"
}

###
POST {{baseUrl}}/project/getProjectList
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "pageIndex": 1,
  "pageSize": 10
}

###
POST {{baseUrl}}/project/updateProject
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "id": 123,
  "projectName": "新名字"
}

###
POST {{projectUrl}}/project/joinProject
Content-Type: application/json
Authorization: {{token}}

{
  "id": 7
}

###
POST {{projectUrl}}/project/getProjectInfo
Content-Type: application/json
Authorization: {{token}}

{
  "id": 7
}