server:
  port: 9010
spring:
  application:
    name: api-manager-zuul
  datasource:
    url: jdbc:mysql://minnan.site:3306/api_manager?serverTimezone=Asia/Shanghai
    username: Minnan
    password: minnan
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 600000
  redis:
    host: minnan.site
    port: 6379
    database: 6
    password: minnan
  cache:
    type: redis
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9030/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
zuul:
  routes:
    api-manager-auth:
      path: /apiManager/auth/**
      serviceId: api-manager-auth
      stripPrefix: false
    api-manager-project:
      path: /apiManager/project/**
      serviceId: api-manager-project
      stripPrefix: false
    api-manager-user:
      path: /apiManager/user/**
      serviceId: api-manager-user
      stripPrefix: false
  sensitive-headers:
    - ${jwt.header}

swagger-doc:
  doc:
    api-manager-auth: http://localhost:9000/v2/api-docs
    api-manager-project: http://localhost:9001/v2/api-docs
    api-manager-user: http://localhost:9002/v2/api-docs

jwt:
  header: token
  expiration: 604800
  secret: min107
  authorized: false