spring:
  application:
    name: api-manager-eureka-server
  datasource:
    url: jdbc:mysql://192.168.6.129:3306/api_manager?serverTimezone=Asia/Shanghai
    username: Minnan
    password: minnan
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 600000
  redis:
    host: 192.168.6.129
    port: 6379
    database: 0
    password: minnan

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:9030/eureka
    register-with-eureka: false
    fetch-registry: false
server:
  port: 9030